<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="Math" Id="{53549243-095a-493a-ab32-c0c5bbf86db2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Math
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="AddInt" Id="{a7dbd43a-20a6-4288-80d8-5bcf4f8bfa94}">
      <Declaration><![CDATA[METHOD AddInt : INT
VAR_INPUT
  a : INT;
  b : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddInt := a + b;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>