name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
      - 'MyApplication/**'
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: Zeugwerk/zkdoc-action@1.0.0
        with:
          username: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
          password: ${{ secrets.ACTIONS_ZGWK_PASSWORD }}
          filepath: MyApplication/MyApplication/MyApplication.plcproj
          working-directory: "MyApplication"
          doc-folder: "../doc"
